export const CATEGORY_OPTIONS = [
  'Elektronika',
  'Telefonlar',
  'Noutbuklar',
  'Aksessuarlar',
  'Maishiy texnika',
  'Erkaklar kiyimi',
  'Ayollar kiyimi',
  'Bolalar kiyimi',
  'Oyoq kiyim',
  "Go'zallik mahsulotlari",
  'Salomatlik',
  "Oziq-ovqat",
  'Ichimliklar',
  'Kitoblar',
  'Sport jihozlari',
  'Avto mahsulotlar',
  'Uy jihozlari',
  'Mebel',
  "O'yinchoqlar",
  'Zargarlik buyumlari',
];
